### ISSUE TITLE
Lower Body Clothing

### ISSUE THREAD

**Issue by gseth** [cozymantis/clothes-swap-salvton-comfyui-workflow#1]
Can this be adapted to work with lower-body clothing?

**Comment by gabidobo** [comment]
The original model has been trained with a bias for upper-body clothes, so lower-body won't work unfortunately.

For lower-body support, but outputs that are less aligned with the original cloth, we recommend https://cozymantis.gumroad.com/l/cozy-swap-clothes-comfyui-node-dressup-tryon-stableviton?layout=profile.
