### ISSUE TITLE
Help Getting Started

### ISSUE THREAD

**Issue by Phando** [cozymantis/clothes-swap-salvton-comfyui-workflow#3]
I purchased your clothing swap workflow and custom nodes a while back and still haven't had a successful execution. I followed the install instructions and have found or replaced all the missing nodes in the workflow. There is a persistent error with the Human Parser. Is it possible to use a different parser/segmenter? Do you offer refunds? Maybe a getting started video would help.

**Comment by gabidobo** [comment]
@Phando sorry to hear you're having trouble! What is the persistent error you're getting?
Maybe something in the troubleshooting section could help? https://github.com/cozymantis/human-parser-comfyui-node?tab=readme-ov-file#windows-troubleshooting
