### ISSUE TITLE
ComfyUI Manager import Failed

### ISSUE THREAD

**Issue by NicolasCampailla** [cozymantis/clothes-swap-salvton-comfyui-workflow#4]
Hello! After trying to install the Cozy Human Parser nodes from the ComfyUI Manager, the nodes do not install and I receiva an "(Import Failed)" error in red while trying to reinstall  the extention from "missing custom nodes" button.

**Comment by gabidobo** [comment]
Hi there! Your ComfyUI startup logs should also display the error that's causing the failed import - please open a new issue in the proper repository (https://github.com/cozymantis/human-parser-comfyui-node) mentioning the error body.
